# Copyright 2022-2025 ETSI SDG TeraFlowSDN (TFS) (https://tfs.etsi.org/)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tfs-ingress-grafana
  namespace: tfs
  annotations:
    # No rewrite-target here. Grafana handles its own sub-path.
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: webuiservice
            port:
              number: 3000
